apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dispatcher
    app.kubernetes.io/managed-by: Helm
  name: dispatcher
spec:
  ports:
    - port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: dispatcher
  type: NodePort
status:
  loadBalancer: {}
