apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-inference
  name: ml-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-inference
  template:
    metadata:
      labels:
        app: ml-inference
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9999"
    spec:
      containers:
        - image: gulzerr/ml-inference:latest
          imagePullPolicy: Always
          name: ml-inference
          ports:
            - containerPort: 9999
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
