apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: inference-autoscaler
  namespace: default
  labels:
    app: inference-autoscaler
spec:
  scaleTargetRef:
    name: ml-inference
  maxReplicaCount: 5
  minReplicaCount: 1
  pollingInterval: 15
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://inference-metrics-prometheus-server:80
        metricName: cpu_usage
        query: sum(irate(process_cpu_seconds_total{app="ml-inference"}[2m])) * 100
        threshold: "50"
