apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ml-inference
    app.kubernetes.io/managed-by: Helm
  name: ml-inference
spec:
  ports:
    - port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: ml-inference
  type: NodePort
status:
  loadBalancer: {}
