prometheus:
  alertmanager:
    enabled: false

  pushgateway:
    enabled: true

  nodeExporter:
    enabled: true

grafana:
  service:
    type: NodePort

  # Add Loki as a datasource
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki-stack:3100
          access: proxy
          isDefault: false

# KEDA is installed separately in keda namespace

# Loki-stack configuration
loki-stack:
  loki:
    persistence:
      enabled: true
      size: 10Gi
  promtail:
    enabled: true
    config:
      clients:
        - url: http://loki-stack:3100/loki/api/v1/push
  grafana:
    enabled: false # We're already using our own Grafana
  prometheus:
    enabled: false # We're already using our own Prometheus
